// One-shot generator for low-quality image placeholders (LQIP) used as
// blurDataURL on banner <Image> components. Run with:
//   node scripts/generate-blur.mjs
//
// Reads each path in BANNERS, makes a 10px-wide webp, base64-encodes it,
// and writes the map to src/data/blurHashes.ts.

import sharp from "sharp";
import { writeFileSync } from "fs";
import { resolve, join } from "path";

const BANNERS = [
  "public/images/hero.jpg",
  "public/images/Research Topic Banner.jpg",
  "public/images/about-us-banner.jpg",
  "public/images/patents-banner.jpg",
  "public/images/Our Mission banner.jpg",
  "public/images/Open positions banner.webp",
  "public/images/join-our-team.jpg",
  "public/images/Team/Team Banner.jpg",
  "public/images/Projects/projects-banner.webp",
  "public/images/Publications/publication-banner.jpg",
  "public/images/news/news-insights-banner.jpg",
  "public/images/Resources/Resources Banner.jpg",
  "public/images/Stats/Mission.jpg",
  "public/images/Stats/Team.jpg",
  "public/images/Stats/ResearchTopic.jpg",
  "public/images/Stats/AboutUs.jpg",
];

const ROOT = resolve(".");
const out = {};

for (const rel of BANNERS) {
  try {
    const abs = join(ROOT, rel);
    const buf = await sharp(abs)
      .resize(12, null, { fit: "inside" })
      .webp({ quality: 40 })
      .toBuffer();
    const publicPath = "/" + rel.replace(/^public\//, "");
    out[publicPath] = `data:image/webp;base64,${buf.toString("base64")}`;
    console.log(`ok  ${publicPath}  (${buf.length}b)`);
  } catch (err) {
    console.warn(`skip ${rel}: ${err.message}`);
  }
}

const ts = `// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Regenerate after adding/replacing banner source images.
export const blurHashes: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;

writeFileSync("src/data/blurHashes.ts", ts);
console.log(`\nwrote src/data/blurHashes.ts with ${Object.keys(out).length} entries`);
