// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Regenerate after adding/replacing banner source images.
export const blurHashes: Record<string, string> = {
  "/images/hero.jpg": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoMAAYAA4BaJZwAAueD/iDlgAD+9LQVQP99H7YMVDwzupBRwAK2WFqGxXlkdTo6AQAAAA==",
  "/images/Research Topic Banner.jpg": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoMAAgAA4BaJbACdLoAAndiDnq4cAD81gppdl+FHvRzbk/W2RHysDFYNrFA/VlON8STxbvk9w5pDHREfL5CwMIP91m8emlWIGAAAA==",
  "/images/about-us-banner.jpg": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAAcAA4BaJZwAAlmX1w6AAP72/SBTf3qTZPZG+4nz9qGmS/8sMx2ryXipC52kBzjI7YAA",
  "/images/patents-banner.jpg": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoMAAcAA4BaJZQAAlm+6CEAAP2S6eR4xorN7rufdjgs9W7XDcDGuaGfna8XAAAA",
  "/images/Our Mission banner.jpg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAMAA4BaJbACdAD8v1TrDgAA/upZLPIQHioRoiaD1ZJS3DRh2GpXbpjHLn4TNMWQbbdagt/UtXiTrWjqAAAA",
  "/images/Open positions banner.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAcAA4BaJZQAD42NahguiAD+vJCeSnt4dOrjTZz0VuWpAJBixfYKh8ntxMnwR0AowXghLKac6gvpuIoAAA==",
  "/images/join-our-team.jpg": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAYAA4BaJZQCdAC8tdBUAAD+4lFdERLbyKt/heRz9ecaGN3yNo8q4S6iYPA3O1A1En3EN6+1bxxY2LtQAA==",
  "/images/Team/Team Banner.jpg": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoMAA8AA4BaJaQAFEB7WmlRSViSIIAA/tuGBkeDxOL8F9z3w2gVZnJjje8za/3ZaFI3eDeRNorFHYVbkWm44akCG7eLgd3P3YSIs+A81jEYqSGZGfB5ZeAPrkAAAA==",
  "/images/Projects/projects-banner.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAYAA4BaJYwCdADyf8OCAAD+3fo13mpfRvFhOZ/RscHmR0PbEoM7rHNnpcAeGUYPt8lT7v9JiloNAhLgnDAA",
  "/images/Publications/publication-banner.jpg": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAgAA4BaJZwAAxaekh9VkADh9wsQmKxC/poQ0aIoO6keTbTXX2JsKLEZ0FAAAAA=",
  "/images/news/news-insights-banner.jpg": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoMAAYAA4BaJZQCdH8AGZCWuArJOAD8Ief/uAxzIcZ5gNLu+tTLSjs5Vfrrb70h325RG4EPAa1KAAAA",
  "/images/Resources/Resources Banner.jpg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoMAAgAA4BaJQBOgCHUqh8AAPaZeiJrcfWGowGibeXG5UQSXFaeY4bucSAMCq3oaG4SZNQb6KqFdHodZO9XwAAA",
  "/images/Stats/Mission.jpg": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwAwCdASoMABIAPu1iqU2ppaOiMAgBMB2JZQAASeU+64XatI/XAAD+ybPaeW4Ggb8JJAhZGiVhYRv7jCJgjDSz5ujv1n2cz9e7zwhb2wHd4R+c641UaW4UabtfpRYM8aSVQjh/JbLlq+o43iIbn3zseR5dKXcyO5k4aTh5ERccAA==",
  "/images/Stats/Team.jpg": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAgCdASoMAAwAA4BaJQBYheADFt+9bjcXYAD++Rx1dJ7CVq2cQDT46pTFeYzaaPwOnBlCnzoDQDDoaAAAAA==",
  "/images/Stats/ResearchTopic.jpg": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAgAA4BaJZQC7AEPCvs/AAD++VGaAMVaun/Fkb3ZSyyjobqsTAAA",
  "/images/Stats/AboutUs.jpg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAAgAA4BaJZQAD4bO1MGBFOwAAP7gyGq6Mp6e6ByxZB9lZ2k88Kbjm0bkt+ttO12IVpmBSdOjx2QT6s7SgAAA"
};
